<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-ScaleAtacado.PrintAgent-761c7265-f49c-4f0a-b110-1c202bcd4786</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.26" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ScaleAtacado.Shared\ScaleAtacado.Shared.csproj" />
    <ProjectReference Include="..\ScaleAtacado.Application\ScaleAtacado.Application.csproj" />
    <ProjectReference Include="..\ScaleAtacado.Domain\ScaleAtacado.Domain.csproj" />
  </ItemGroup>
</Project>
