services:
  postgres-db:
    image: postgres:15-alpine
    container_name: scale_atacado_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Scale@123
      POSTGRES_DB: scale_atacado
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: