<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Validators\" />
    <Folder Include="UseCases\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ScaleAtacado.Domain\ScaleAtacado.Domain.csproj" />
    <ProjectReference Include="..\ScaleAtacado.Shared\ScaleAtacado.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.11.0" />
  </ItemGroup>

</Project>
